name: project cicd
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: deply
    runs-on: ubuntu-latest
    steps:
      - name: run ssh
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 130
          script:
            echo "qwer1234" | sudo -S bash -c
            cd /tmp;
            git clone https://github.com/raccoon-coding/CiCD.git;
            cd CiCD;
            chmod 777 ./gradlew;
            ./gradlew bootjar;
            docker build -t cicd .;
            docker run -p 8080:8080 -d --name testCicd cicd;
          
